version: "3.8"

services:
  # PostgreSQL Database (Development)
  postgres:
    image: postgres:15-alpine
    container_name: langclash_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: langclash_dev
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: langclash_dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - langclash_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langclash_dev -d langclash_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (Development)
  redis:
    image: redis:7-alpine
    container_name: langclash_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - langclash_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL Admin Interface (Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: langclash_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@langclash.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - langclash_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  langclash_network:
    driver: bridge
